#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>

static void
usage(const char *argv0)
{
  fprintf(stderr, "Usage: %s -o output.c -d depfile.d -p prefix file1 [file2 ...]\n",
          argv0);
  exit(1);
}

static char *
make_symbol_name(const char *name)
{
  char *sym = strdup(name);
  for(char *p = sym; *p; p++) {
    if(!((*p >= 'a' && *p <= 'z') ||
         (*p >= 'A' && *p <= 'Z') ||
         (*p >= '0' && *p <= '9')))
      *p = '_';
  }
  return sym;
}

int
main(int argc, char **argv)
{
  const char *output = NULL;
  const char *depfile = NULL;
  const char *prefix = NULL;
  int first_file = 0;

  for(int i = 1; i < argc; i++) {
    if(!strcmp(argv[i], "-o") && i + 1 < argc) {
      output = argv[++i];
    } else if(!strcmp(argv[i], "-d") && i + 1 < argc) {
      depfile = argv[++i];
    } else if(!strcmp(argv[i], "-p") && i + 1 < argc) {
      prefix = argv[++i];
    } else {
      first_file = i;
      break;
    }
  }

  if(!output || !depfile || !prefix || !first_file)
    usage(argv[0]);

  // Find common directory prefix to strip from filenames
  const char *strip_prefix = argv[first_file];
  for(int i = first_file; i < argc; i++) {
    const char *a = strip_prefix;
    const char *b = argv[i];
    int common = 0;
    while(*a && *b && *a == *b) {
      if(*a == '/')
        common = a - strip_prefix + 1;
      a++;
      b++;
    }
    // Truncate strip_prefix to common length
    // We need to allocate since we're modifying it
    if(i == first_file) {
      // For single file or first iteration, find last '/' in the path
      const char *last_slash = strrchr(strip_prefix, '/');
      if(last_slash)
        strip_prefix = strndup(strip_prefix, last_slash - strip_prefix + 1);
      else
        strip_prefix = "";
    } else {
      char *tmp = strndup(strip_prefix, common);
      strip_prefix = tmp;
    }
  }

  int strip_len = strlen(strip_prefix);

  FILE *out = fopen(output, "w");
  if(!out) {
    fprintf(stderr, "mkembed: Unable to open %s: %s\n", output, strerror(errno));
    exit(1);
  }

  fprintf(out, "// Generated by mkembed - do not edit\n");
  fprintf(out, "#include <stddef.h>\n");
  fprintf(out, "#include \"libsvc/filebundle.h\"\n\n");

  // Emit data arrays
  for(int i = first_file; i < argc; i++) {
    const char *path = argv[i];
    const char *name = path + strip_len;
    char *sym = make_symbol_name(name);

    FILE *in = fopen(path, "rb");
    if(!in) {
      fprintf(stderr, "mkembed: Unable to open %s: %s\n", path, strerror(errno));
      fclose(out);
      exit(1);
    }

    fseek(in, 0, SEEK_END);
    long size = ftell(in);
    fseek(in, 0, SEEK_SET);

    fprintf(out, "static const unsigned char data_%s[] = {", sym);

    unsigned char buf[4096];
    long total = 0;
    size_t n;
    while((n = fread(buf, 1, sizeof(buf), in)) > 0) {
      for(size_t j = 0; j < n; j++) {
        if(total % 12 == 0)
          fprintf(out, "\n ");
        fprintf(out, " 0x%02x,", buf[j]);
        total++;
      }
    }
    fclose(in);

    fprintf(out, "\n};\n\n");
    free(sym);
  }

  // Emit entries table
  fprintf(out, "static const struct filebundle_entry entries[] = {\n");
  for(int i = first_file; i < argc; i++) {
    const char *path = argv[i];
    const char *name = path + strip_len;
    char *sym = make_symbol_name(name);
    FILE *in = fopen(path, "rb");
    fseek(in, 0, SEEK_END);
    long size = ftell(in);
    fclose(in);
    fprintf(out, "  {\"%s\", data_%s, %ld, -1},\n", name, sym, size);
    free(sym);
  }
  fprintf(out, "  {NULL, NULL, 0, 0}\n");
  fprintf(out, "};\n\n");

  // Emit bundle struct and constructor
  fprintf(out, "static struct filebundle bundle = {\n");
  fprintf(out, "  .entries = entries,\n");
  fprintf(out, "  .prefix = \"%s\"\n", prefix);
  fprintf(out, "};\n\n");

  fprintf(out, "static void __attribute__((constructor)) register_bundle(void) {\n");
  fprintf(out, "  extern struct filebundle *filebundles;\n");
  fprintf(out, "  bundle.next = filebundles;\n");
  fprintf(out, "  filebundles = &bundle;\n");
  fprintf(out, "}\n");

  fclose(out);

  // Write dependency file
  FILE *dep = fopen(depfile, "w");
  if(!dep) {
    fprintf(stderr, "mkembed: Unable to open %s: %s\n", depfile, strerror(errno));
    exit(1);
  }

  fprintf(dep, "%s:", output);
  for(int i = first_file; i < argc; i++)
    fprintf(dep, " %s", argv[i]);
  fprintf(dep, "\n");

  // Empty targets for each file (gcc -MP style)
  for(int i = first_file; i < argc; i++)
    fprintf(dep, "%s:\n", argv[i]);

  fclose(dep);

  return 0;
}
